import { Person, FamilyTree } from "./types";

const members: Person[] = [
  // ========== 20세 ==========
  {
    id: "p1",
    nameKorean: "원부",
    nameHanja: "原頫",
    courtesyName: "원부(원부)",
    penName: "운암",
    generation: 20,
    gender: "male",
    isLiving: false,
    position: "고려 공민왕 간의대부 종3품",
    bio: "문절공 원부파 시조, 왕권을 견제하는 언론(言論) 기능, 조선시대 사간원",
    childrenIds: ["p2"],
  },

  // ========== 21세 ==========
  {
    id: "p2",
    nameKorean: "안경",
    nameHanja: "安卿",
    courtesyName: "홍(弘)정",
    generation: 21,
    gender: "male",
    isLiving: false,
    position: "세종 좌찬성 세조 2품",
    fatherId: "p1",
    childrenIds: ["p3"],
  },

  // ========== 22세 ==========
  {
    id: "p3",
    nameKorean: "상도",
    nameHanja: "尙道",
    courtesyName: "달(達)포",
    generation: 22,
    gender: "male",
    isLiving: false,
    position: "고려 공민왕 을유생",
    bio: "배 포도(浦道) 상도",
    fatherId: "p2",
    childrenIds: ["p4"],
  },

  // ========== 23세 ==========
  {
    id: "p4",
    nameKorean: "계생",
    nameHanja: "繼生",
    courtesyName: "술(述)지",
    generation: 23,
    gender: "male",
    isLiving: false,
    position: "성균 진사",
    bio: "묘 태조 정축생",
    fatherId: "p3",
    spouseIds: ["s4"],
    childrenIds: ["p5"],
  },
  {
    id: "s4",
    nameKorean: "경주 금씨",
    generation: 23,
    gender: "female",
    isLiving: false,
    spouseClan: "경주 금씨",
    spouseIds: ["p4"],
  },

  // ========== 24세 ==========
  {
    id: "p5",
    nameKorean: "경철",
    nameHanja: "敬轍",
    courtesyName: "찬옥(贊玉)",
    penName: "업암(業菴)",
    generation: 24,
    gender: "male",
    isLiving: false,
    birthDateSolar: "중종 계묘",
    bio: "중종 계묘년 8월 9일생",
    fatherId: "p4",
    spouseIds: ["s5"],
    childrenIds: ["p6"],
    burialLocation: "상동 하조",
  },
  {
    id: "s5",
    nameKorean: "양천 허씨",
    generation: 24,
    gender: "female",
    isLiving: false,
    spouseClan: "양천 허씨",
    burialLocation: "상동 상 하조",
    spouseIds: ["p5"],
  },

  // ========== 25세 ==========
  {
    id: "p6",
    nameKorean: "희동",
    nameHanja: "希東",
    courtesyName: "인거(寅擧)",
    generation: 25,
    gender: "male",
    isLiving: false,
    birthDateSolar: "중종 경오",
    deathDateSolar: "선묘 계사",
    position: "중종 경오년 8월 9일생",
    bio: "선묘 계사 3월 20일졸",
    fatherId: "p5",
    spouseIds: ["s6"],
    childrenIds: ["p7"],
  },
  {
    id: "s6",
    nameKorean: "순창 림씨",
    generation: 25,
    gender: "female",
    isLiving: false,
    spouseClan: "순창 림씨",
    spouseIds: ["p6"],
  },

  // ========== 26세 ==========
  {
    id: "p7",
    nameKorean: "적손",
    nameHanja: "迪遜",
    courtesyName: "혜(惠)걸(傑)",
    generation: 26,
    gender: "male",
    isLiving: false,
    birthDateSolar: "중종 병인",
    deathDateSolar: "을해",
    fatherId: "p6",
    spouseIds: ["s7"],
    childrenIds: ["p8", "p9"],
  },
  {
    id: "s7",
    nameKorean: "밀양 박씨",
    generation: 26,
    gender: "female",
    isLiving: false,
    spouseClan: "밀양 박씨",
    spouseIds: ["p7"],
  },

  // ========== 27세 ==========
  {
    id: "p8",
    nameKorean: "덕현",
    nameHanja: "德賢",
    courtesyName: "여덕(汝德)",
    generation: 27,
    gender: "male",
    isLiving: false,
    birthDateSolar: "명종 갑인",
    deathDateSolar: "기해",
    burialLocation: "강진 만덕산",
    burialDirection: "경좌",
    fatherId: "p7",
    spouseIds: ["s8"],
    childrenIds: ["p10", "p11"],
  },
  {
    id: "s8",
    nameKorean: "천안 금씨",
    generation: 27,
    gender: "female",
    isLiving: false,
    spouseClan: "천안 금씨",
    burialLocation: "강진 만덕산 경좌",
    spouseIds: ["p8"],
  },
  {
    id: "p9",
    nameKorean: "복현",
    nameHanja: "復賢",
    courtesyName: "치현(致賢)",
    generation: 27,
    gender: "male",
    isLiving: false,
    burialLocation: "강진",
    fatherId: "p7",
  },

  // ========== 28세 ==========
  {
    id: "p10",
    nameKorean: "귀운",
    nameHanja: "龜雲",
    generation: 28,
    gender: "male",
    isLiving: false,
    bio: "귀운, 귀악, 귀봉, 귀락 4형제",
    fatherId: "p8",
    childrenIds: ["p12"],
  },
  {
    id: "p11",
    nameKorean: "귀봉",
    nameHanja: "龜峯",
    courtesyName: "고(高)서(瑞)",
    generation: 28,
    gender: "male",
    isLiving: false,
    position: "진사",
    burialLocation: "상동",
    fatherId: "p8",
  },

  // ========== 29세 ==========
  {
    id: "p12",
    nameKorean: "유현",
    nameHanja: "有鉉",
    courtesyName: "광삼(光三)",
    penName: "삼봉삼(三峯三)",
    generation: 29,
    gender: "male",
    isLiving: false,
    position: "성균 진사",
    fatherId: "p10",
    spouseIds: ["s12"],
    childrenIds: ["p13"],
  },
  {
    id: "s12",
    nameKorean: "광산 금씨",
    generation: 29,
    gender: "female",
    isLiving: false,
    spouseClan: "광산 금씨",
    burialLocation: "상동 합조",
    spouseIds: ["p12"],
  },

  // ========== 30세 ==========
  {
    id: "p13",
    nameKorean: "영위",
    nameHanja: "迎位",
    courtesyName: "선(先)",
    penName: "선복(先復)",
    generation: 30,
    gender: "male",
    isLiving: false,
    burialLocation: "상동 선영 하",
    fatherId: "p12",
    childrenIds: ["p14"],
  },

  // ========== 31세 ==========
  {
    id: "p14",
    nameKorean: "두지",
    nameHanja: "斗智",
    courtesyName: "두지(斗智)",
    generation: 31,
    gender: "male",
    isLiving: false,
    birthDateSolar: "임신 9월 17일",
    deathDateSolar: "갑자",
    position: "숙종 송당",
    burialLocation: "장흥 정동",
    burialDirection: "서좌",
    burialJoint: "쌍조",
    fatherId: "p13",
    spouseIds: ["s14"],
    childrenIds: ["p15"],
  },
  {
    id: "s14",
    nameKorean: "금해 금씨",
    generation: 31,
    gender: "female",
    isLiving: false,
    spouseClan: "금해 금씨",
    burialLocation: "장흥 정동 서좌 쌍조",
    spouseIds: ["p14"],
  },

  // ========== 32세 ==========
  {
    id: "p15",
    nameKorean: "태인",
    nameHanja: "泰仁",
    courtesyName: "광거(廣巨)",
    generation: 32,
    gender: "male",
    isLiving: false,
    burialLocation: "강진 호계 토봉",
    burialDirection: "해좌",
    burialJoint: "쌍조",
    fatherId: "p14",
    spouseIds: ["s15"],
    childrenIds: ["p16"],
  },
  {
    id: "s15",
    nameKorean: "안산 이씨",
    generation: 32,
    gender: "female",
    isLiving: false,
    spouseClan: "안산 이씨",
    burialLocation: "강진 호계 토봉 해좌 쌍조",
    spouseIds: ["p15"],
  },

  // ========== 33세 ==========
  {
    id: "p16",
    nameKorean: "진필",
    nameHanja: "進弼",
    courtesyName: "공신식(公愼)",
    generation: 33,
    gender: "male",
    isLiving: false,
    deathDateSolar: "7월 5일",
    bio: "진명(進猛)이라고도 함",
    burialLocation: "칠량 서면",
    burialJoint: "쌍조",
    fatherId: "p15",
    spouseIds: ["s16"],
    childrenIds: ["p17"],
  },
  {
    id: "s16",
    nameKorean: "진주 강씨",
    generation: 33,
    gender: "female",
    isLiving: false,
    spouseClan: "진주 강씨",
    deathDateSolar: "5월 20일",
    burialLocation: "칠량 서면 쌍조",
    spouseIds: ["p16"],
  },

  // ========== 34세 ==========
  {
    id: "p17",
    nameKorean: "원중",
    nameHanja: "元仲",
    courtesyName: "군걸(君傑)",
    generation: 34,
    gender: "male",
    isLiving: false,
    deathDateSolar: "1월 27일",
    burialLocation: "칠량 서면 명오리",
    bio: "감주",
    fatherId: "p16",
    spouseIds: ["s17"],
    childrenIds: ["p18"],
  },
  {
    id: "s17",
    nameKorean: "제주 양씨",
    generation: 34,
    gender: "female",
    isLiving: false,
    spouseClan: "제주 양씨",
    bio: "기사 4월 20일",
    burialLocation: "칠량 서면 명오리 감주",
    spouseIds: ["p17"],
  },

  // ========== 35세 ==========
  {
    id: "p18",
    nameKorean: "천륜",
    nameHanja: "千輪",
    courtesyName: "여백(汝伯)",
    generation: 35,
    gender: "male",
    isLiving: false,
    birthDateSolar: "영묘 을묘",
    deathDateSolar: "병자 12월",
    position: "증 통정대부",
    bio: "영묘 을묘생, 병자 12월 1일졸",
    burialLocation: "상동",
    burialJoint: "쌍조",
    fatherId: "p17",
    spouseIds: ["s18"],
    childrenIds: ["p19"],
  },
  {
    id: "s18",
    nameKorean: "평택 림씨",
    generation: 35,
    gender: "female",
    isLiving: false,
    spouseClan: "평택 림씨",
    burialLocation: "상동 쌍조",
    spouseIds: ["p18"],
  },

  // ========== 36세 ==========
  {
    id: "p19",
    nameKorean: "계도",
    nameHanja: "啓導",
    courtesyName: "운직(雲直)",
    generation: 36,
    gender: "male",
    isLiving: false,
    birthDateSolar: "정미",
    deathDateSolar: "정미",
    position: "통정대부",
    bio: "영묘 중생, 정미 1월 23일생, 정미 8월 9일 졸",
    burialLocation: "칠량 서면 명오리",
    fatherId: "p18",
    spouseIds: ["s19"],
    childrenIds: ["p20"],
  },
  {
    id: "s19",
    nameKorean: "금해 금씨",
    generation: 36,
    gender: "female",
    isLiving: false,
    spouseClan: "금해 금씨",
    bio: "기사 7월 9일",
    burialLocation: "칠량 서면 명오리 감주",
    spouseIds: ["p19"],
  },

  // ========== 37세 ==========
  {
    id: "p20",
    nameKorean: "명석",
    nameHanja: "命錫",
    courtesyName: "수익(守益)",
    generation: 37,
    gender: "male",
    isLiving: false,
    birthDateSolar: "계사 3월",
    deathDateSolar: "신묘 12월",
    bio: "계사 3월 28일생, 신묘 12월 졸",
    burialLocation: "관봉 견기 선영 하",
    fatherId: "p19",
    childrenIds: ["p21"],
  },

  // ========== 38세 ==========
  {
    id: "p21",
    nameKorean: "오준",
    nameHanja: "五濬",
    courtesyName: "내오(乃五)",
    penName: "세록(世錄)",
    generation: 38,
    gender: "male",
    isLiving: false,
    birthDateSolar: "1849-12-01",
    deathDateSolar: "1896-08-16",
    burialLocation: "경기 광주 오포 시안가족묘원",
    fatherId: "p20",
    childrenIds: ["p22"],
  },

  // ========== 39세 ==========
  {
    id: "p22",
    nameKorean: "만종",
    nameHanja: "萬鍾",
    courtesyName: "태옥(太玉)",
    penName: "영수(榮洙)",
    generation: 39,
    gender: "male",
    isLiving: false,
    birthDateSolar: "1885-07-23",
    deathDateSolar: "1941-12-24",
    bio: "배 이천 서씨 봉업 1891년 신묘 4월 5일졸",
    burialLocation: "강진 이번지 산",
    burialJoint: "쌍조",
    fatherId: "p21",
    childrenIds: ["p23"],
  },

  // ========== 40세 ==========
  {
    id: "p23",
    nameKorean: "승환",
    nameHanja: "承煥",
    courtesyName: "창환(昌煥)",
    generation: 40,
    gender: "male",
    isLiving: false,
    birthDateSolar: "1927-12-19",
    deathDateSolar: "2018-11-15",
    position: "월동상사 대표이사",
    fatherId: "p22",
    spouseIds: ["s23"],
    childrenIds: ["p24", "p25", "p26", "p27", "p28"],
  },
  {
    id: "s23",
    nameKorean: "김차심",
    generation: 40,
    gender: "female",
    isLiving: false,
    birthDateSolar: "1929-04-25",
    deathDateSolar: "1986-05-13",
    spouseClan: "금해 김씨",
    bio: "강진읍 신학리 출신",
    burialLocation: "상동",
    spouseIds: ["p23"],
  },

  // ========== 41세 ==========
  {
    id: "p24",
    nameKorean: "재배",
    nameHanja: "載培",
    courtesyName: "현배(炫培)",
    generation: 41,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1947-12-19",
    position: "제이씨현시스템 ㈜ 대표이사",
    fatherId: "p23",
    spouseIds: ["s24"],
    childrenIds: ["p29", "p30"],
  },
  {
    id: "s24",
    nameKorean: "장혜숙",
    generation: 41,
    gender: "female",
    isLiving: true,
    birthDateSolar: "1952-09-24",
    spouseIds: ["p24"],
  },
  {
    id: "p25",
    nameKorean: "길재",
    nameHanja: "吉宰",
    courtesyName: "길재",
    generation: 41,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1955-08-04",
    position: "대아리드선 ㈜ 대표이사",
    fatherId: "p23",
    spouseIds: ["s25"],
    childrenIds: ["p31", "p32"],
  },
  {
    id: "s25",
    nameKorean: "서태수",
    generation: 41,
    gender: "female",
    isLiving: true,
    birthDateSolar: "1960-07-08",
    bio: "1960년 경자 7월 8일생",
    spouseIds: ["p25"],
  },
  {
    id: "p26",
    nameKorean: "중석",
    nameHanja: "重錫",
    generation: 41,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1959-07-20",
    position: "시에스아이 이노베이션 ㈜ 대표이사",
    fatherId: "p23",
    spouseIds: ["s26"],
    childrenIds: ["p33", "p34"],
  },
  {
    id: "s26",
    nameKorean: "이혜정",
    generation: 41,
    gender: "female",
    isLiving: true,
    birthDateSolar: "1965-03-23",
    spouseIds: ["p26"],
  },
  {
    id: "p27",
    nameKorean: "미숙",
    nameHanja: "美淑",
    courtesyName: "미숙",
    generation: 41,
    gender: "female",
    isLiving: true,
    birthDateSolar: "1961-04-20",
    fatherId: "p23",
    spouseIds: ["s27"],
  },
  {
    id: "s27",
    nameKorean: "강재덕",
    generation: 41,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1962-01-20",
    spouseIds: ["p27"],
  },
  {
    id: "p28",
    nameKorean: "미영",
    nameHanja: "美英",
    courtesyName: "미영",
    generation: 41,
    gender: "female",
    isLiving: true,
    birthDateSolar: "1967-11-21",
    fatherId: "p23",
    spouseIds: ["s28"],
  },
  {
    id: "s28",
    nameKorean: "윤상혁",
    generation: 41,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1965-03-04",
    spouseIds: ["p28"],
  },

  // ========== 42세 ==========
  {
    id: "p29",
    nameKorean: "예원",
    nameHanja: "睿媛",
    generation: 42,
    gender: "female",
    isLiving: true,
    birthDateSolar: "1979-11-10",
    fatherId: "p24",
    spouseIds: ["s29"],
  },
  {
    id: "s29",
    nameKorean: "은시형",
    generation: 42,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1974-01-02",
    spouseIds: ["p29"],
  },
  {
    id: "p30",
    nameKorean: "정헌",
    nameHanja: "定憲",
    generation: 42,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1981-01-26",
    fatherId: "p24",
    spouseIds: ["s30"],
    childrenIds: ["p35", "p36"],
  },
  {
    id: "s30",
    nameKorean: "윤희영",
    generation: 42,
    gender: "female",
    isLiving: true,
    birthDateSolar: "1982",
    spouseIds: ["p30"],
  },
  {
    id: "p31",
    nameKorean: "형주",
    nameHanja: "炯周",
    courtesyName: "형주",
    generation: 42,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1984-07-09",
    fatherId: "p25",
  },
  {
    id: "p32",
    nameKorean: "승훈",
    nameHanja: "承勳",
    generation: 42,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1986-01-02",
    fatherId: "p25",
  },
  {
    id: "p33",
    nameKorean: "상훈",
    nameHanja: "相勳",
    generation: 42,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1992-01-04",
    fatherId: "p26",
  },
  {
    id: "p34",
    nameKorean: "상민",
    nameHanja: "相敏",
    courtesyName: "상민",
    generation: 42,
    gender: "male",
    isLiving: true,
    birthDateSolar: "1994-04-23",
    fatherId: "p26",
  },

  // ========== 43세 ==========
  {
    id: "p35",
    nameKorean: "윤재",
    nameHanja: "允載",
    generation: 43,
    gender: "male",
    isLiving: true,
    fatherId: "p30",
  },
  {
    id: "p36",
    nameKorean: "윤호",
    nameHanja: "允浩",
    generation: 43,
    gender: "male",
    isLiving: true,
    fatherId: "p30",
  },
];

export const familyTree: FamilyTree = {
  clanName: "연안 차씨 문절공 원부파 가승",
  originPlace: "연안",
  founderName: "차원부(車原頫)",
  members,
};

export function getPerson(id: string): Person | undefined {
  return familyTree.members.find((m) => m.id === id);
}

export function getChildren(personId: string): Person[] {
  return familyTree.members.filter((m) => m.fatherId === personId);
}

export function getSpouse(person: Person): Person | undefined {
  if (!person.spouseIds?.length) return undefined;
  return familyTree.members.find((m) => m.id === person.spouseIds![0]);
}

export function getRootMembers(): Person[] {
  return familyTree.members.filter(
    (m) => !m.fatherId && !m.motherId && m.gender === "male"
  );
}
